# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Charon < Formula
  desc "Switch Codex, Claude Code and OpenCode between endpoint + credential profiles"
  homepage "https://github.com/mingtheanlay/charon"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_darwin_amd64.tar.gz"
      sha256 "24d774b56585fad0bc3260ec3ee93c83e8bd61de46166bb554f0ab99078d3367"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_darwin_arm64.tar.gz"
      sha256 "02817b8f4861e7b4cd732f1bcbf2add7721f5f43ce3bece5bbf0bb366359658a"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_linux_amd64.tar.gz"
      sha256 "0bdf918279f01dc44c197170d4766169a0ad0d6eb6203270865ef9d504908af0"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_linux_arm64.tar.gz"
      sha256 "24f6f32fbcbab8e9bf860a6d1d213f33eef2b594054a0bd1ef7f34d9df8077c1"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Not using Homebrew? Install with one line on Linux or macOS:
        curl -fsSL https://github.com/mingtheanlay/charon/releases/latest/download/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/charon", "--help"
  end
end
