# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Charon < Formula
  desc "Switch Codex, Claude Code and OpenCode between endpoint + credential profiles"
  homepage "https://github.com/mingtheanlay/charon"
  version "1.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.3/charon_darwin_amd64.tar.gz"
      sha256 "ccf787b4803920d3302a94cde9d1d9a2092ef0b4386d5abca8bd4694c9c6739c"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.3/charon_darwin_arm64.tar.gz"
      sha256 "748419e17c8671f041112b0e2c4168da2d90851e2a24229a5e9e82c29175a752"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.3/charon_linux_amd64.tar.gz"
      sha256 "b0b43e0894a5b9c5a138ba12c584c2406854d349b26a824ee52589626d06feff"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.3/charon_linux_arm64.tar.gz"
      sha256 "018e4258caa86fa6a53ccc77449b7a930da6e4c2106db9f36bfdadf30b37ea9a"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Not using Homebrew? Install with one line on Linux or macOS:
        curl -fsSL https://github.com/mingtheanlay/charon/releases/latest/download/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/charon", "--help"
  end
end
