# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Charon < Formula
  desc "Switch Codex, Claude Code and OpenCode between endpoint + credential profiles"
  homepage "https://github.com/mingtheanlay/charon"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_darwin_amd64.tar.gz"
      sha256 "6e66b9156a935703e496d2eaf09a83b3abdab7a92d7c8a33fd0047c2f684cc1b"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_darwin_arm64.tar.gz"
      sha256 "1f0f981900a2e6f8354578997577e66147d49fb9017a621bb0aa1245dcd5ffc0"

      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_linux_amd64.tar.gz"
      sha256 "cadd0706a1353bc0272171ce09051300aa8dc71c517336e66227873af139e738"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mingtheanlay/charon/releases/download/v1.3.1/charon_linux_arm64.tar.gz"
      sha256 "e200446eee5f99525b2885574d1cf2d3c76eccc34e9b5aa0cc31727847c808cd"
      define_method(:install) do
        bin.install "charon"
        bash_completion.install "completions/charon.bash" => "charon"
        zsh_completion.install "completions/charon.zsh" => "_charon"
        fish_completion.install "completions/charon.fish"
      end
    end
  end

  def caveats
    <<~EOS
      Not using Homebrew? Install with one line on Linux or macOS:
        curl -fsSL https://github.com/mingtheanlay/charon/releases/latest/download/install.sh | sh
    EOS
  end

  test do
    system "#{bin}/charon", "--help"
  end
end
