# This file was generated by GoReleaser. DO NOT EDIT.
cask "charon" do
  version "1.3.8"

  on_macos do
    on_intel do
      sha256 "ef4bef926fb056fced810edb3b23e74b0b30f328d5649380582a778746d901ba"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1918c49e3ee3e2cf6414a179f05f30f1471a17bdba889656ca8a6982eddfb46f"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a24c25df56053dc7df4da42e9e6b7ffbe7d620b50397d4876a52172a84c5392a"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3eb3436bce0a2f24915ab102402977121de4264ef2acb6b603f15e3d830857b"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_linux_arm64.tar.gz"
    end
  end

  name "charon"
  desc "Switch Codex, Claude Code and OpenCode between endpoint + credential profiles"
  homepage "https://github.com/mingtheanlay/charon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charon"
  bash_completion "completions/charon.bash"
  fish_completion "completions/charon.fish"
  zsh_completion "completions/charon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charon"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Not using Homebrew? Install with one line on Linux or macOS:
      curl -fsSL https://github.com/mingtheanlay/charon/releases/latest/download/install.sh | sh
  EOS
end
