# This file was generated by GoReleaser. DO NOT EDIT.
cask "charon" do
  version "1.3.9"

  on_macos do
    on_intel do
      sha256 "7283a6b8cf87328388bf5f5f6c18beb5d033c73214156b1a43184b00097502cc"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce2c4afca83db8ea1a98ef94aa8781031c824056c0369b24b7d1fc9a73eebe66"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40c29284ef8be0646bcbc421964aa6a5d714cda075fcc5547f8ea6a295ae1415"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "04dc8091f6daabeacf783223fc80139ca14a64685c9fda72bd91b4d95911a3a8"
      url "https://github.com/mingtheanlay/charon/releases/download/v#{version}/charon_linux_arm64.tar.gz"
    end
  end

  name "charon"
  desc "Switch Codex, Claude Code and OpenCode between endpoint + credential profiles"
  homepage "https://github.com/mingtheanlay/charon"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charon"
  bash_completion "completions/charon.bash"
  fish_completion "completions/charon.fish"
  zsh_completion "completions/charon.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charon"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Not using Homebrew? Install with one line on Linux or macOS:
      curl -fsSL https://github.com/mingtheanlay/charon/releases/latest/download/install.sh | sh
  EOS
end
